### ISSUE TITLE
Can't See uploaded file on my drive

### ISSUE THREAD

**Issue by Sparshagarwal12** [myvsparth/flutter_gdrive#2]
The program is working perfect but when i open my drive i can't see the files those i have upload through  app.

**Comment by eugenepangue** [comment]
i know it is in hidden folder. but can you teach us how to upload file to a specific folder in gdrive? thanks in advance.

**Comment by gautamenbake** [comment]
yes pls tell us how to upload file to a specific folder in gdrive...

**Comment by yusmi25** [comment]
same issue
